/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.178.0Release
// Tag = production/release/21.178.0-0-g3bea629
/////////////////////////////////////////////////////////////////////////////////////////////

public enum FaveroProduct: UInt16, CaseIterable {
    case assiomaUno = 10
    case assiomaDuo = 12
    case invalid = 0xFFFF
}
