/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.178.0Release
// Tag = production/release/21.178.0-0-g3bea629
/////////////////////////////////////////////////////////////////////////////////////////////

public enum MaxMetHeartRateSource: UInt8, CaseIterable {
    case whr = 0
    case hrm = 1
    case invalid = 0xFF
}
