/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.170.0Release
// Tag = production/release/21.170.0-0-g5991e72
/////////////////////////////////////////////////////////////////////////////////////////////

public enum TapSensitivity: UInt8, CaseIterable {
    case high = 0
    case medium = 1
    case low = 2
    case invalid = 0xFF
}
